### ISSUE TITLE
Media Test implementations package

### ISSUE THREAD

**Issue by OmerBenD** [app-central/love-triangle#1]
In order for the game to have all the relevant SDKs for the media test, please implement the unity package (sent to you over Slack along with this issue) and follow the instructions (also sent over Slack in pdf).
Please make sure you activate only phase 1.

See below the relevant keys:
AppsFlyer: cKCUQ38QmEpeatEyGr3CeV
GameAnalytics game key: f7753e484c1c46d945937cad0a990d9c
GameAnalytics secret key: fc027b00cd5efb7361dce105c1e9931895b74b29
Smartlook project key: 73bc8925df66a7289bf07db29aec81a86a3cc730

**Comment by OmerBenD** [comment]
v 20.0.1:
1. GameAnalytics is not implemented
2. Smartlook is not implemented
3. AppsFlyer is not implemented

**Comment by MayaAnto** [comment]
v21.0.0 (2):
1. Smartlook is not implemented
2. AppsFlyer not working/not implemented

**Comment by OmerBenD** [comment]
22.0.0 (3):
1. There are no events in the session
