### ISSUE TITLE
Marketing Implementations Package

### ISSUE THREAD

**Issue by OmerBenD** [app-central/love-triangle#4]
In order to prepare the game to be included in a bundle and begin marketing it, please follow the instructions (attached in the Slack message) to activate Phase-2 of the implementations package.
Also attached in the Slack message:
Updated provisioning profiles.

See below the relevant keys for Phase-2:
AppLovin:
key: X4PxbyMNSE4K_UW5tdAUJG5rdaW1M5w4BU4NQc9r8b-OtuyBeqRMN3df1upuhRLgbvurdfyc3hSwZdImXetnxA
Banner ad unit - f1ded4a61438687f
Interstitial ad unit - efbbe63a4f61a76f
Rewarded ad unit - d0fdf5207f5da4da
App open ad unit - 1b7994e617b77d52

banner:
at the bottom at all times (just make sure it doesn't block content/links), except when the paywall is showing

rewarded:
on all rewarded buttons **and when the user fails (in order to get revived)**.

interstitials:
put an interstitial ad at the end of every level

OneSignal app id:
ac0c3582-375c-4d69-a181-7f6983b7376f

*Regarding the default paywall, you need to place a "no ads" button in the home screen, that when the user clicks on it, will open the default paywall.

**make sure that users that subscribes to our IAP must receive the following:
remove the "no ads" button for them
remove all the paywall for them
remove the banner and interstitial ads for them
all items in the shop (if there is a shop in the game) must be available and unlocked for them

**Comment by MayaAnto** [comment]
25.0.0 (6):
Checked only IAP and default paywall:
1. IAP - not approved, missing metadata 
2. default paywall - Tapping the no-ads button doesn't open the paywall

**Comment by MayaAnto** [comment]
v26.0.0 (7):
1. It seems like the bright data is not implemented, there is no permission screen and no web-indexing.
2. There is no app rating prompt

**Comment by MayaAnto** [comment]
v30.0.0 (11):
1. Please add text under the web-indexing "Enable to support the app"

**Comment by MayaAnto** [comment]
Working in v 31.0.0 (12)
